const Privacy = () => {
  return (
    <div className="bg-white py-24">
      <div className="container mx-auto px-6">
        <header className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gradient">Privacy Policy</h1>
          <p className="mt-4 text-gray-600">Effective Date: January 6, 2025</p>
        </header>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Introduction</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules made there under as applicable and
            the provisions about electronic records in various statutes as
            amended by the Information Technology Act, 2000. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures to make the terms of this policy
            binding. BOS Center Private Limited, a company incorporated under
            the Companies Act, 1956 having its registered office at Plot No.
            118, First Floor, Kakrola Housing Complex, Near Dwarka Mor Metro
            Station, Sector-15, Dwarka, New Delhi, India, 110078 (hereinafter
            referred to as &quot;BOS Center&quot;) owns and operates
            https://bos.center (&quot;Website/Platform&quot;). At BOS Center,
            data protection is a matter of trust and your privacy is very
            important to us. We use your personal information only in the manner
            as set out in this Privacy Policy. Please read this Privacy Policy
            to learn more about our information-gathering and dissemination
            practices. This Privacy Policy explains how BOS Center through its
            Platform/Website gathers personal information, as part of the normal
            operation of services; and uses discloses and protects such
            information through the Website/Platform. This detailed Privacy
            Policy enables you to make informed decisions in dealings with us.
            Our privacy practices are subject to the requirements of applicable
            law. By registering with the Website/Platform, you acknowledge your
            acceptance of the terms of this Privacy Policy, expressly consent to
            our use and disclosure of your personal information by this Privacy
            Policy and that any personal information provided by you to BOS
            Center is provided under a lawful contract. You are also authorizing
            BOS Center&apos;s employees and its partners to call, SMS and email
            you. This Privacy Policy is incorporated into the Platform/Website
            available at the following link https://www.bos.center/ Note: Our
            privacy policy is subject to changes at any time without notice. To
            make sure you are aware of any changes, please review this policy
            periodically.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Your Privacy</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            At BOS Center, we are extremely proud of our commitment to protect
            your privacy. We value your trust in us. We work hard to earn your
            confidence so that you can enthusiastically use our services and
            recommend others to participate in dealing with us. Please read the
            following policy to understand how your personal information will be
            treated as you make full use of our Website. For this Privacy
            Policy, &quot;users&quot; (also referred to as &quot;you&quot;,
            &quot;your&quot;, and &quot;user&quot;) shall mean all such persons
            having access to the Platform of BOS Center and/or persons availing
            services offered through the Platform or otherwise including without
            limitation BOS Center&apos;s service providers, end customers and/or
            any third party using or accessing the BOS Center Platform/Website.{" "}
            <br />
            <strong>BOS Center Privacy Assurance,</strong> We promise that we
            will not sell or rent your personal information to third parties or
            use the same for unsolicited emails or messages without your
            explicit consent. From time to time we may reveal general
            statistical information about our Platform/Website and visitors,
            such as number of visitors, services purchased, etc. Your trust and
            confidence are our highest priority.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Information that the BOS Center Collects
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            When you use our Platform/Website or services offered through the
            Platform/Website, we collect and store your personal information to
            record, support and facilitate your participation in the services to
            provide you with a customized site experience to notify you of any
            updated information. We collect your information mainly to provide
            the service requested by you. It is used for initial service
            provision and ongoing User support. The information can also be used
            by the BOS Center for sending periodic emails announcing important
            service changes, new features, technical issue updates news, etc.
            The Users may decide NOT to receive such emails by replying to any
            of them with &quot;Unsubscribe&quot; in the subject. The information
            is also used for purposes like improving the efficiency and
            effectiveness of the Platform/Website.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Information collected by the BOS Center
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            BOS Center collects Users&apos; personal information to provide
            services to the Users. These include, but are not limited to: name,
            mailing address, telephone numbers, email addresses, and other
            information that may be needed for providing the services requested
            by the User. All this information is provided voluntarily by the
            User through various order forms, email messages sent to the BOS
            Center, submission of forms, identification/registration forms,
            due-diligence processes, information provided over the telephone, or
            through the procedure undertaken for e-KYC of the user etc. We also
            collect different types of non-personally information about our
            Platform/Website visitors. These include but are not limited to
            referral URLs, Users&apos; IP addresses, Users&apos; use of the
            Website, information about the browsers used by the User, etc. Some
            of this information is collected through cookies, which are small
            pieces of data that are sent to your browser from a web server and
            are stored on your computer&apos;s hard drive and help us identify
            the User. The user has the choice to modify his/her browser and thus
            reject our cookies.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Our use of your information
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We use your personal information to facilitate the Services you
            request. We do not sell, rent, trade or exchange any personally
            identifying information of our Users. We may provide your collected
            information to our affiliates and service providers under contract
            (such as customer care, and data analytics) to support the operation
            of the Platform/Website and our services. To the extent we use your
            personal information, we will provide you with the ability to opt
            out of such uses. We use your personal information to: resolve
            disputes; troubleshoot problems; help promote safe transactions;
            collect fees owed; measure user interest in the services provided by
            us, inform you about online and offline services and updates;
            customize your experience; detect and protect us against error,
            fraud and other criminal activity and as otherwise described to you
            at the time of collection. In our efforts to continually improve our
            service offerings, we also collect and analyze demographic, account
            and usage data about our users&apos; activity on our
            Platform/Website. <br />
            We may also use your personal information to display content and
            services that are targeted to your interests. By accepting the Terms
            and Privacy Policy, you expressly agree to receive this information.
            If you do not wish to receive these communications, we encourage you
            to opt out of the receipt of certain communications by clicking
            unsubscribe from any email communication or writing back an email to
            us. You may make changes to the data in your account at any time.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Disclosure of information
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            Your personal information is an important part of our business and
            we are not in the business of selling it to others. We only share
            information as per the rules or conditions described below:
          </p>
          <ul className="list-disc ml-6 mt-4 text-gray-600">
            <li>
              Any disclosure of information to a third party will be on the
              prior permission of yours
            </li>
            <li>
              We will not be requesting any prior permission in case where you
              have agreed to disclosure by way of contract earlier.
            </li>
            <li>
              We will not be requesting any prior permission in cases for
              complying with legal requirements.
            </li>
          </ul>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We may use your information for new, unanticipated uses not
            previously disclosed in our privacy notice. If our information
            practices change at some time in the future we will contact you
            before we use your data for these new purposes to notify you of the
            policy change and to provide you with the ability to opt out of
            these new uses. <br />
            On request we may provide any site visitors with access to all
            information, they have provided to us, which we maintain about them.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Data Retention & Deletion
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            BOS Center Pvt. Ltd. may store your Personal Information (including
            Sensitive Personal Information) for 30 days which is permissible as
            per the applicable laws in India for the purposes for which we
            collected it & delete it after the retention period. The retention
            of Personal Information (including Sensitive Personal Information)
            by BOS Center is determined by considering compliance with legal
            (that is, contractual or statutory, or regulatory requirements),
            accounting, and compliance reporting requirements.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Security</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            To protect your privacy and security, we always use
            industry-standard encryption technologies when transferring and
            receiving user data exchanged with our site. We always abide by the
            security standard, provided under the Information Technology Act,
            2000 read with Information Technology (Reasonable Security Practices
            and Procedures for Protection of Sensitive Personal Data and
            Information) Rules, 2011.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Advertisements on Website
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We use third-party advertising companies to serve ads when you visit
            our Website. These companies may use your information (not including
            your name, address, email address, telephone number, or usage data)
            about your visits to this and other websites to provide
            advertisements about services of interest to you. Since we do not
            control the privacy practices of these advertisers, you should
            evaluate their practices before deciding to provide the said
            information.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Links to Other Sites
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            Our Website may contain links to other websites or frames of other
            sites that may collect personally identifiable information about
            you. Please be aware that BOS Center is not responsible for the
            privacy practices or the content of those linked websites.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Amendments</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            BOS Center reserves the right to revise its policies at any time
            without prior notice. <br />
            By the Information Technology Act, 2000 and the rules made there
            under, the name and contact details of the Nodal desk are published
            herewith: <br />
            <strong>
              Nodal Desk- Monday to Saturday from 10:00 a.m. to 8:00 p.m.
            </strong>
            <br />
            Building No. 73, Block B-1, Sewak Park Extension, Near NSUT, Uttam
            Nagar, New Delhi - 110059 <br />
            Email us your suggestions/queries/complaints at info@bos.center.
            <br />
            If you do not want to receive e-mail from us in the future, please
            let us know by sending us e-mail at info@bos.center <br />
            <strong>
              YOU ACKNOWLEDGE AND AGREE THAT ANY DISPUTE OVER PRIVACY IS SUBJECT
              TO THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY, AS WELL AS, IF
              APPLICABLE, THE TERMS OF USE BETWEEN YOU AND PAYSPRINT. YOU AND WE
              EACH SUBMIT TO THE EXCLUSIVE JURISDICTION OF THE INDIAN COURTS IN
              DELHI ABOUT DISPUTES ARISING IN CONNECTION WITH THIS PRIVACY
              POLICY.
            </strong>
          </p>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
